apiVersion: batch/v1
kind: Job
metadata:
  generateName: integration-test-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: pi
          image: busybox
          command: ["wget", "guestbook-ui:81"]
      restartPolicy: Never
  backoffLimit: 4
